### ISSUE TITLE
Reason for using uint64_t  instead  of uint32_t

### ISSUE THREAD

**Issue by macxfadz** [Bestoa/huffman-codec#1]
Can you explain why did you use **uint64_t** data type instead of 4 byte **uint32_t** data type?

- If we use ,

`struct huffman_node {
    uint32_t weight;
    uint8_t value;
    struct huffman_node *left;
    struct huffman_node *right;
};`

instead of,

`struct huffman_node {
    uint64_t weight;
    uint8_t value;
    struct huffman_node *left;
    struct huffman_node *right;
};`

will algorithm break due to **huffman node weight** attribute's size change?

**Comment by Bestoa** [comment]
For large file(>4GB).

**Comment by macxfadz** [comment]
Thanks for the answer Bestoa, by the way If I change whole system from uint64 to uint32 algo' is n't breaking right,especially building huff-tree ?
